language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_e38084c2971e_key -iv $encrypted_e38084c2971e_iv
  -in regex-design-f5d1e9618ad1.json.enc -out regex-design-f5d1e9618ad1.json -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_deploy:
- npm run-script build
- mkdir deploy
- cp -a dist deploy/dist
- cp -a app.yaml deploy
- cd deploy
deploy:
    provider: gae
    skip_cleanup: true
    keyfile: regex-design-f5d1e9618ad1.json
    default: true
    project: regex-design
    on: dev
