language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_e38084c2971e_key -iv $encrypted_e38084c2971e_iv
  -in regex-design-f5d1e9618ad1.json.enc -out regex-design-f5d1e9618ad1.json -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_deploy:
- npm run-script build
- rm -rf node_modules
- rm -rf src
- rm -rf coverage
- rm -rf e2e
- rm .editorconfig
- rm .gitignore
- rm .hgignore
- rm angular-cli.json
- rm app_deploy.sh
- rm karma.conf.sh
- rm package.json
- rm protractor.conf.js
- rm README.md
- rm regex-design-f5d1e9618ad1.json.enc
- rm tslint.json
deploy:
    provider: gae
    skip_cleanup: true
    keyfile: regex-design-f5d1e9618ad1.json
    default: true
    project: regex-design
    on: dev
