language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_e38084c2971e_key -iv $encrypted_e38084c2971e_iv
  -in regex-design-f5d1e9618ad1.json.enc -out regex-design-f5d1e9618ad1.json -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_deploy:
- npm run-script build
- rm -rf node_modules && rm -rf src && rm -rf coverage && rm -rf e2e
- rm -f .editorconfig && rm -f .gitignore && rm -f .hgignore && rm -f angular-cli.json && rm -f app_deploy.sh && rm -f karma.conf.js && rm -f package.json && rm -f protractor.conf.js && rm -f README.md && rm -f regex-design-f5d1e9618ad1.json.enc && rm -f tslint.json
deploy:
    provider: gae
    skip_cleanup: true
    keyfile: regex-design-f5d1e9618ad1.json
    default: true
    project: regex-design
    on: dev
