runtime: python27
threadsafe: true

handlers:

# LetsEncrypt handler
- url: /\.well-known/acme-challenge/(.+)
  upload: letsencrypt/(.+)
  static_files: letsencrypt/\1
  mime_type: text/plain

- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

- url: /
  static_dir: dist/
  secure: always
